name = "PersonalWebsite-Backend-Worker"
main = "src/index.js"        
type= "javascript"
compatibility_date = "2026-01-01"


[[d1_databases]]
binding = "DB"
database_name = "personal-website-sql"
database_id = "27bdb95a-3ec9-4feb-9306-294226f93fb6"