name = "PersonalWebsite-Backend-Worker"
main = "src/index.js"        
type= "javascript"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "personal-website-sql"
database_id = "27bdb95a-3ec9-4feb-9306-294226f93fb6"

send_email = [
    {name = "emailWorker", destination_address = "natdrone101@gmail.com"},
]